name: 🔍 Debug Deployment Issues

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  debug:
    name: Debug Deployment Configuration
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug Environment Variables
        run: |
          echo "🔍 Debugging Deployment Configuration"
          echo "======================================"
          
          # Check if secrets are available (without revealing values)
          echo "📋 Checking secrets availability:"
          if [ -n "${{ secrets.AWS_REGION }}" ]; then
            echo "✅ AWS_REGION: Available"
          else
            echo "❌ AWS_REGION: Missing"
          fi
          
          if [ -n "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then
            echo "✅ AWS_ACCESS_KEY_ID: Available"
          else
            echo "❌ AWS_ACCESS_KEY_ID: Missing"
          fi
          
          if [ -n "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]; then
            echo "✅ AWS_SECRET_ACCESS_KEY: Available"
          else
            echo "❌ AWS_SECRET_ACCESS_KEY: Missing"
          fi
          
          if [ -n "${{ secrets.AMPLIFY_APP_ID }}" ]; then
            echo "✅ AMPLIFY_APP_ID: Available"
          else
            echo "❌ AMPLIFY_APP_ID: Missing"
          fi
          
          if [ -n "${{ secrets.AMPLIFY_BRANCH }}" ]; then
            echo "✅ AMPLIFY_BRANCH: Available (${{ secrets.AMPLIFY_BRANCH }})"
          else
            echo "❌ AMPLIFY_BRANCH: Missing"
          fi
          
          if [ -n "${{ secrets.AMPLIFY_WEBHOOK_URL }}" ]; then
            echo "✅ AMPLIFY_WEBHOOK_URL: Available"
          else
            echo "❌ AMPLIFY_WEBHOOK_URL: Missing"
          fi
          
          if [ -n "${{ secrets.S3_DEV_BUCKET }}" ]; then
            echo "✅ S3_DEV_BUCKET: Available"
          else
            echo "❌ S3_DEV_BUCKET: Missing"
          fi
          
          if [ -n "${{ secrets.ENABLE_S3 }}" ]; then
            echo "✅ ENABLE_S3: Available (${{ secrets.ENABLE_S3 }})"
          else
            echo "❌ ENABLE_S3: Missing"
          fi

      - name: Test AWS Connection
        if: secrets.AWS_ACCESS_KEY_ID != ''
        run: |
          echo "🔧 Testing AWS Connection..."
          
          # Configure AWS credentials
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_REGION }}
          
          # Test AWS CLI
          echo "Testing AWS CLI..."
          aws sts get-caller-identity || echo "❌ AWS authentication failed"
          
          # Test Amplify access
          if [ -n "${{ secrets.AMPLIFY_APP_ID }}" ]; then
            echo "Testing Amplify access..."
            aws amplify get-app --app-id "${{ secrets.AMPLIFY_APP_ID }}" || echo "❌ Amplify app access failed"
          fi

      - name: Check Current Branch
        run: |
          echo "📋 Current branch: $(git branch --show-current)"
          echo "📋 Remote branches:"
          git branch -r
          
      - name: Debug Summary
        run: |
          echo "## 🔍 Deployment Debug Summary" > $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Repository:** Adarshktiwarii/Product-Manager-Portfolio" >> $GITHUB_STEP_SUMMARY
          echo "**Current Branch:** $(git branch --show-current)" >> $GITHUB_STEP_SUMMARY
          echo "**Latest Commit:** $(git log -1 --oneline)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 🔧 Configuration Status:" >> $GITHUB_STEP_SUMMARY
          echo "- AWS Credentials: $([ -n '${{ secrets.AWS_ACCESS_KEY_ID }}' ] && echo '✅ Available' || echo '❌ Missing')" >> $GITHUB_STEP_SUMMARY
          echo "- Amplify App ID: $([ -n '${{ secrets.AMPLIFY_APP_ID }}' ] && echo '✅ Available' || echo '❌ Missing')" >> $GITHUB_STEP_SUMMARY
          echo "- Amplify Branch: $([ -n '${{ secrets.AMPLIFY_BRANCH }}' ] && echo '✅ Available' || echo '❌ Missing')" >> $GITHUB_STEP_SUMMARY
          echo "- S3 Bucket: $([ -n '${{ secrets.S3_DEV_BUCKET }}' ] && echo '✅ Available' || echo '❌ Missing')" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 🎯 Next Steps:" >> $GITHUB_STEP_SUMMARY
          echo "1. Check GitHub repository secrets" >> $GITHUB_STEP_SUMMARY
          echo "2. Verify AWS Amplify app configuration" >> $GITHUB_STEP_SUMMARY
          echo "3. Ensure branch mapping is correct" >> $GITHUB_STEP_SUMMARY
